version: "3"
services:
  db:
    image: postgres:14.2-alpine
    container_name: demo-postgres-14.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: "postgres -c 'max_connections=500'"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "ecomicx@docker.com"
      PGADMIN_DEFAULT_PASSWORD: "admin@docker123"
    ports:
      - "5055:80"
    depends_on:
      - db
  web:
    build: .
    tty: true
    stdin_open: true
    restart: always
    command: >
      sh -c "bundle install &&
             bundle exec rails db:create &&
             bundle exec rails db:migrate &&
             bundle exec rails db:seed &&
             rm -f tmp/pids/server.pid &&
             RAILS_SERVE_STATIC_FILES=false bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    volumes:
      - .:/api
    depends_on:
      - db
    ports:
      - "3000:3000"

volumes:
  postgres_data: {}
  api: {}
