default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['POSTGRES_HOST'] %>
  port: 5432

# development:
#   <<: *default
#   database: ecomicx_development
#   username: <%= ENV['POSTGRES_USER'] %>
#   password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  adapter: sqlite3
  encoding: unicode
  database: ecomicx_development
  pool: 5

test:
  <<: *default
  database: ecomicx_test
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

production:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
